version: 2


jobs:
  build:
    docker:
      - image: circleci/node:12.18
    
    steps:
      - checkout
      - run: |
          cd api
          npm ci
      - run: cd api && npm test

      - setup_remote_docker

      - run: |
          cd api
          TAG="0.1.${CIRCLE_BUILD_NUM}"
          docker build -t crshlab/cicd_b:$TAG .
          docker login -u $DOCKER_LOGIN -p $DOCKER_PASS
          docker push crshlab/cicd_b:$TAG
          docker tag crshlab/cicd_b:$TAG crshlab/cicd_b:latest
          docker push crshlab/cicd_b:latest